![Growdev](https://www.growdev.com.br/assets/images/logo_growdev.png)

![Formação Engenharia de Dados](https://d335luupugsy2.cloudfront.net/cms/files/524558/1707226566/$occu5m8t1op)

# Tópicos da Aula de Hoje

- DQL
- Funções Agregação
- ORDER BY
- Exercícios

**Bora pra aula?**

# DQL

A DQL, linguagem de consulta de dados, é utilizada justamente para este fim. O comando chave dentro de DQL é:
- ```SELECT``` - Usado para buscar dados em tabelas


## SQLite

In [1]:
import sqlite3
import pandas as pd

In [2]:
con = sqlite3.connect('./database.db')
csqlite = con.cursor()

In [3]:
query = """
        SELECT tbl_name FROM sqlite_master where type='table'
        """
csqlite.execute(query)
tabelas = csqlite.fetchall()
tabelas

[('my_table',),
 ('countries',),
 ('customers',),
 ('employees',),
 ('offices',),
 ('orderdetails',),
 ('orders',),
 ('payments',),
 ('productlines',),
 ('products',)]

In [4]:
query2 = "PRAGMA table_info(employees)"
csqlite.execute(query2);
info = csqlite.fetchall()
info

[(0, 'employeeNumber', 'int(11)', 1, None, 1),
 (1, 'lastName', 'varchar(50)', 1, None, 0),
 (2, 'firstName', 'varchar(50)', 1, None, 0),
 (3, 'extension', 'varchar(10)', 1, None, 0),
 (4, 'email', 'varchar(100)', 1, None, 0),
 (5, 'officeCode', 'varchar(10)', 1, None, 0),
 (6, 'reportsTo', 'int(11)', 0, 'NULL', 0),
 (7, 'jobTitle', 'varchar(50)', 1, None, 0)]

In [5]:
query1 = """
        SELECT tbl_name FROM sqlite_master where type='table'
        """
df_tabelas = pd.read_sql(query1,con)
df_tabelas

tbl_name
0      my_table
1     countries
2     customers
3     employees
4       offices
5  orderdetails
6        orders
7      payments
8  productlines
9      products

In [6]:
query2 = "PRAGMA table_info(employees)"
info_df = pd.read_sql(query2,con)
info_df

cid            name          type  notnull dflt_value  pk
0    0  employeeNumber       int(11)        1       None   1
1    1        lastName   varchar(50)        1       None   0
2    2       firstName   varchar(50)        1       None   0
3    3       extension   varchar(10)        1       None   0
4    4           email  varchar(100)        1       None   0
5    5      officeCode   varchar(10)        1       None   0
6    6       reportsTo       int(11)        0       NULL   0
7    7        jobTitle   varchar(50)        1       None   0

In [7]:
query3 = "SELECT * FROM products"
products = pd.read_sql(query3,con)
products

productCode                            productName   productLine  \
0      S10_1678  1969 Harley Davidson Ultimate Chopper   Motorcycles   
1      S10_1949               1952 Alpine Renault 1300  Classic Cars   
2      S10_2016                  1996 Moto Guzzi 1100i   Motorcycles   
3      S10_4698   2003 Harley-Davidson Eagle Drag Bike   Motorcycles   
4      S10_4757                    1972 Alfa Romeo GTA  Classic Cars   
..          ...                                    ...           ...   
105   S700_3505                            The Titanic         Ships   
106   S700_3962                         The Queen Mary         Ships   
107   S700_4002              American Airlines: MD-11S        Planes   
108    S72_1253                       Boeing X-32A JSF        Planes   
109    S72_3212                             Pont Yacht         Ships   

    productScale              productVendor  \
0           1:10            Min Lin Diecast   
1           1:10    Classic Metal Creations   
2           1:10   Highway 66 Mini Classics   
3           1:10          Red Start Diecast   
4           1:10    Motor City Art Classics   
..           ...                        ...   
105        1:700   Carousel DieCast Legends   
106        1:700  Welly Diecast Productions   
107        1:700        Second Gear Diecast   
108         1:72    Motor City Art Classics   
109         1:72       Unimax Art Galleries   

                                    productDescription  quantityInStock  \
0    This replica features working kickstand, front...             7933   
1    Turnable front wheels; steering function; deta...             7305   
2    Official Moto Guzzi logos and insignias, saddl...             6625   
3    Model features, official Harley Davidson logos...             5582   
4    Features include: Turnable front wheels; steer...             3252   
..                                                 ...              ...   
105  Completed model measures 19 1/2 inches long, 9...             1956   
106  Exact replica. Wood and Metal. Many extras inc...             5088   
107  Polished finish. Exact replia with official lo...             8820   
108  10\" Wingspan with retractable landing gears.C...             4857   
109  Measures 38 inches Long x 33 3/4 inches High. ...              414   

     buyPrice    MSRP  
0       48.81   95.70  
1       98.58  214.30  
2       68.99  118.94  
3       91.02  193.66  
4       85.68  136.00  
..        ...     ...  
105     51.09  100.17  
106     53.63   99.31  
107     36.27   74.03  
108     32.77   49.66  
109     33.30   54.60  

[110 rows x 9 columns]

## SELECT FROM

O primeiro comando que iremos mostrar é o ```SELECT``` ```FROM```. A sintaxe para esse comando é:
```sql
SELECT coluna1, coluna2,..., colunan
FROM table1
```

Precisamos informar as colunas que queremos trazer e a tabela que contém essas colunas.

In [8]:
query = """
SELECT firstName, email
FROM employees
LIMIT 10
"""
df_employee = pd.read_sql(query,con)
df_employee

firstName                            email
0     Diane     dmurphy@classicmodelcars.com
1      Mary   mpatterso@classicmodelcars.com
2      Jeff   jfirrelli@classicmodelcars.com
3   William  wpatterson@classicmodelcars.com
4    Gerard     gbondur@classicmodelcars.com
5   Anthony        abow@classicmodelcars.com
6    Leslie   ljennings@classicmodelcars.com
7    Leslie   lthompson@classicmodelcars.com
8     Julie   jfirrelli@classicmodelcars.com
9     Steve  spatterson@classicmodelcars.com

In [9]:
query3 = "SELECT * FROM products"
products = pd.read_sql(query3,con)
products

productCode                            productName   productLine  \
0      S10_1678  1969 Harley Davidson Ultimate Chopper   Motorcycles   
1      S10_1949               1952 Alpine Renault 1300  Classic Cars   
2      S10_2016                  1996 Moto Guzzi 1100i   Motorcycles   
3      S10_4698   2003 Harley-Davidson Eagle Drag Bike   Motorcycles   
4      S10_4757                    1972 Alfa Romeo GTA  Classic Cars   
..          ...                                    ...           ...   
105   S700_3505                            The Titanic         Ships   
106   S700_3962                         The Queen Mary         Ships   
107   S700_4002              American Airlines: MD-11S        Planes   
108    S72_1253                       Boeing X-32A JSF        Planes   
109    S72_3212                             Pont Yacht         Ships   

    productScale              productVendor  \
0           1:10            Min Lin Diecast   
1           1:10    Classic Metal Creations   
2           1:10   Highway 66 Mini Classics   
3           1:10          Red Start Diecast   
4           1:10    Motor City Art Classics   
..           ...                        ...   
105        1:700   Carousel DieCast Legends   
106        1:700  Welly Diecast Productions   
107        1:700        Second Gear Diecast   
108         1:72    Motor City Art Classics   
109         1:72       Unimax Art Galleries   

                                    productDescription  quantityInStock  \
0    This replica features working kickstand, front...             7933   
1    Turnable front wheels; steering function; deta...             7305   
2    Official Moto Guzzi logos and insignias, saddl...             6625   
3    Model features, official Harley Davidson logos...             5582   
4    Features include: Turnable front wheels; steer...             3252   
..                                                 ...              ...   
105  Completed model measures 19 1/2 inches long, 9...             1956   
106  Exact replica. Wood and Metal. Many extras inc...             5088   
107  Polished finish. Exact replia with official lo...             8820   
108  10\" Wingspan with retractable landing gears.C...             4857   
109  Measures 38 inches Long x 33 3/4 inches High. ...              414   

     buyPrice    MSRP  
0       48.81   95.70  
1       98.58  214.30  
2       68.99  118.94  
3       91.02  193.66  
4       85.68  136.00  
..        ...     ...  
105     51.09  100.17  
106     53.63   99.31  
107     36.27   74.03  
108     32.77   49.66  
109     33.30   54.60  

[110 rows x 9 columns]

In [10]:
query3 = """
SELECT productCode
, productName
, productLine
, buyPrice
FROM products
"""
products = pd.read_sql(query3,con)
products

productCode                            productName   productLine  buyPrice
0      S10_1678  1969 Harley Davidson Ultimate Chopper   Motorcycles     48.81
1      S10_1949               1952 Alpine Renault 1300  Classic Cars     98.58
2      S10_2016                  1996 Moto Guzzi 1100i   Motorcycles     68.99
3      S10_4698   2003 Harley-Davidson Eagle Drag Bike   Motorcycles     91.02
4      S10_4757                    1972 Alfa Romeo GTA  Classic Cars     85.68
..          ...                                    ...           ...       ...
105   S700_3505                            The Titanic         Ships     51.09
106   S700_3962                         The Queen Mary         Ships     53.63
107   S700_4002              American Airlines: MD-11S        Planes     36.27
108    S72_1253                       Boeing X-32A JSF        Planes     32.77
109    S72_3212                             Pont Yacht         Ships     33.30

[110 rows x 4 columns]

## WHERE

Até agora trouxemos todos os registros ou os n primeiros registros. Mas e se quisermos  fazer algum filtro?

```sql
SELECT coluna1, coluna2,..., colunan
FROM table1
WHERE condicao1
```

In [11]:
query3 = """
SELECT productCode
, productName
, productLine
, buyPrice
FROM products
where productLine = 'Motorcycles'
"""
products = pd.read_sql(query3,con)
products

productCode                            productName  productLine  buyPrice
0     S10_1678  1969 Harley Davidson Ultimate Chopper  Motorcycles     48.81
1     S10_2016                  1996 Moto Guzzi 1100i  Motorcycles     68.99
2     S10_4698   2003 Harley-Davidson Eagle Drag Bike  Motorcycles     91.02
3     S12_2823                       2002 Suzuki XREO  Motorcycles     66.27
4     S18_2625    1936 Harley Davidson El Knucklehead  Motorcycles     24.23
5     S18_3782                       1957 Vespa GS150  Motorcycles     32.95
6     S24_1578                      1997 BMW R 1100 S  Motorcycles     60.86
7     S24_2000               1960 BSA Gold Star DBD34  Motorcycles     37.32
8     S24_2360                1982 Ducati 900 Monster  Motorcycles     47.10
9     S32_1374                       1997 BMW F650 ST  Motorcycles     66.92
10    S32_2206                      1982 Ducati 996 R  Motorcycles     24.14
11    S32_4485              1974 Ducati 350 Mk3 Desmo  Motorcycles     56.13
12    S50_4713                     2002 Yamaha YZR M1  Motorcycles     34.17

Podemos utilizar as palavras chave ```OR``` e ```AND``` para construir filtros mais complexos.

In [12]:
query3 = """
SELECT productCode
, productName
, productLine
, buyPrice
FROM products
where productLine = 'Motorcycles'
and productName like '%Harley%'
"""
products = pd.read_sql(query3,con)
products

productCode                            productName  productLine  buyPrice
0    S10_1678  1969 Harley Davidson Ultimate Chopper  Motorcycles     48.81
1    S10_4698   2003 Harley-Davidson Eagle Drag Bike  Motorcycles     91.02
2    S18_2625    1936 Harley Davidson El Knucklehead  Motorcycles     24.23

In [13]:
query = """
SELECT *
FROM payments
WHERE customerNumber = 124 OR customerNumber = 131 AND amount <=30000
"""

df_payments = pd.read_sql(query,con)
df_payments

customerNumber checkNumber paymentDate     amount
0             124    AE215433  2005-03-05  101244.59
1             124    BG255406  2004-08-28   85410.87
2             124    CQ287967  2003-04-11   11044.30
3             124     ET64396  2005-04-16   83598.04
4             124    HI366474  2004-12-27   47142.70
5             124     HR86578  2004-11-02   55639.66
6             124    KI131716  2003-08-15  111654.40
7             124    LF217299  2004-03-26   43369.30
8             124    NT141748  2003-11-25   45084.38
9             131    CL442705  2003-03-12   22292.62

Note que a query retorna os regitros onde customerNumber = 124 ou 131, mas a última condição só é aplicada para o último customerNumber.
Como resolver isso?

In [14]:
query = """
SELECT *
FROM payments
WHERE (customerNumber = 124 OR customerNumber = 131)
AND amount <=30000
"""

df_payments = pd.read_sql(query,con)
df_payments

customerNumber checkNumber paymentDate    amount
0             124    CQ287967  2003-04-11  11044.30
1             131    CL442705  2003-03-12  22292.62

> ATENÇÃO: Sempre use parênteses para especificar a ordem de aplicação dos filtros.

Poderíamos atingir o mesmo resultado passando uma lista de customerNumber e utilizando a função ```IN```

In [15]:
query = """
SELECT *
FROM payments
WHERE (customerNumber in (124, 131))
AND amount <=30000
"""

df_payments = pd.read_sql(query,con)
df_payments

customerNumber checkNumber paymentDate    amount
0             124    CQ287967  2003-04-11  11044.30
1             131    CL442705  2003-03-12  22292.62

# AGG (MAX, MIN, DISTINCT, COUNT, SUM, STD, AVG)

Essas funções trazem resumos de colunas. Por exemplo, podemos calcular a média de alguma coluna ou trazer seu valor máximo e mínimo.

```sql
SELECT FUNC1(coluna1), FUNC2(coluna2),
FROM table1
```

In [16]:
query="""
SELECT MAX(amount) AS MAX_AMOUNT, AVG(amount) AS AVG_AMOUNT
FROM payments
"""
df_amount_max_avg = pd.read_sql(query,con)
df_amount_max_avg

MAX_AMOUNT    AVG_AMOUNT
0   120166.58  32431.645531

# ORDER BY

Podemos ordernar as tabelas e nossas queries com o comando ```ORDER BY```

```sql
SELECT coluna1, coluna2,..., colunan
FROM table1
ORDER BY coluna1
```

In [17]:
query = """
SELECT *
FROM payments
WHERE customerNumber IN (124,131)
ORDER BY customerNumber DESC, paymentDate ASC
"""

df_payments2 = pd.read_sql(query,con)
df_payments2

customerNumber checkNumber paymentDate     amount
0              131    CL442705  2003-03-12   22292.62
1              131    NB445135  2004-09-11   35321.97
2              131    MA724562  2004-12-02   50025.35
3              124    CQ287967  2003-04-11   11044.30
4              124    KI131716  2003-08-15  111654.40
5              124    NT141748  2003-11-25   45084.38
6              124    LF217299  2004-03-26   43369.30
7              124    BG255406  2004-08-28   85410.87
8              124     HR86578  2004-11-02   55639.66
9              124    HI366474  2004-12-27   47142.70
10             124    AE215433  2005-03-05  101244.59
11             124     ET64396  2005-04-16   83598.04

# Exercícios

* Traga os valores máximo, mínimo, total e a quantidade de pagamentos realizados para cada empregado em uma única tabela.

In [18]:
query = '''
SELECT c.customerNumber, 
    c.employeeNumber, 
    c.firstName,
    c.lastName,
    MAX(p.amount) as "Max Amount",
    MIN(p.amount) as "Min Amount",
    SUM(p.amount) as "Total Amount",
    COUNT(c.customerNumber) as "Num Payments"
    FROM (SELECT c.customerNumber, e.employeeNumber, e.firstName, e.lastName from customers as c 
        INNER JOIN employees as e 
        ON c.salesRepEmployeeNumber = e.employeeNumber
    ) as c
    INNER JOIN payments as p
    ON c.customerNumber = p.customerNumber
    GROUP BY c.employeeNumber;
'''

df_payments_by_employee = pd.read_sql_query(query, con)
df_payments_by_employee

customerNumber  employeeNumber firstName   lastName  Max Amount  \
0              161            1165    Leslie   Jennings   111654.40   
1              219            1166    Leslie   Thompson    80375.24   
2              204            1188     Julie   Firrelli    59265.14   
3              198            1216     Steve  Patterson    63357.13   
4              456            1286  Foon Yue      Tseng    58841.35   
5              486            1323    George     Vanauf    50025.35   
6              350            1337      Loui     Bondur    51209.58   
7              103            1370    Gerard  Hernandez   120166.58   
8              381            1401    Pamela   Castillo    53959.21   
9              489            1501     Larry       Bott    52825.29   
10             121            1504     Barry      Jones    85024.46   
11             114            1611      Andy     Fixter    82261.22   
12             323            1612     Peter      Marsh    75020.13   
13             398            1621      Mami      Nishi   105743.00   
14             216            1702    Martin     Gerard    61402.00   

    Min Amount  Total Amount  Num Payments  
0      2434.25     989906.55            21  
1      3452.75     347533.03            13  
2      4424.40     386663.20            14  
3      5858.56     449219.13            15  
4      1679.92     488212.67            17  
5      5899.38     584406.80            20  
6      1834.56     569485.75            19  
7      1676.14    1112003.81            29  
8      1128.20     750201.87            27  
9      7310.42     686653.25            21  
10     1491.38     637672.65            21  
11     7565.08     509385.82            16  
12     2880.00     497907.16            14  
13      615.45     457110.07            14  
14     3101.40     387477.47            12

* Retorne uma tabela contendo os datas e a quantidade de pagamentos ordenada pela quantidade de pagamentos de maneira decrescente.

In [20]:
query = '''
SELECT 
    p.paymentDate as "Payment Date",
    COUNT(*) as "Qtd Payments"
FROM payments p
GROUP BY p.paymentDate
ORDER BY "Qtd Payments" DESC;

'''

df_payments_by_employee = pd.read_sql_query(query, con)
df_payments_by_employee

Payment Date  Qtd Payments
0     2004-06-21             3
1     2003-12-09             3
2     2003-11-24             3
3     2003-11-18             3
4     2005-05-19             2
..           ...           ...
227   2003-02-20             1
228   2003-02-16             1
229   2003-01-30             1
230   2003-01-28             1
231   2003-01-16             1

[232 rows x 2 columns]